name: "Client CI Pipeline"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["nightly"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          profile: minimal
          override: true
      - name: Create .env file
        run: |
          cat > .env << EOF
          PUBLIC_API_URL=temp

          EOF

      - name: Build (ignore warnings)
        run: cargo build --release
        env:
          RUSTFLAGS: "--cap-lints allow"
      - name: cargo test
        run: RUSTFLAGS="-A unsafe-op-in-unsafe-fn" cargo test
