name: Docker CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
        cat > .env << EOF
        PUBLIC_API_URL=temp
        EOF

    - name: Build Docker image
      run: |
        docker build -t client-test .

    - name: Run Docker container
      run:  docker run -d --name client-test -p 3000:3000  client-test

    - name: Wait for containers to initialize
      run: sleep 10

    - name: Stop container
      if: always()
      run: docker stop client-test

    - name: Remove container
      if: always()
      run: docker rm client-test